print('-' * 50)
print(f'{"Descrevendo Strings":^50}')
print('-' * 50)
frase = str(input('Digite algo: ')).strip().title()
frase1 = frase.split()
print(f'Em letras Maiúsculas: {frase.upper()}')
print(f'Em letras Minúsculas: {frase.lower()}')
print(f'Como lista {frase1}')
print(f'Primeiro Palavra: {frase1[0]}')
print(f'Último Palavra: {frase1[-1]}')